config/routes.rb
Rails.application.routes.draw do
  resources :crafts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "crafts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/craft.rb
class Craft < ApplicationRecord
  validates_presence_of :name
  has_rich_text :description
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/crafts_controller.rb
class CraftsController < ApplicationController
  before_action :set_craft, only: %i[ show edit update destroy ]

  # GET /crafts or /crafts.json
  def index
    @crafts = Craft.all
  end

  # GET /crafts/1 or /crafts/1.json
  def show
  end

  # GET /crafts/new
  def new
    @craft = Craft.new
  end

  # GET /crafts/1/edit
  def edit
  end

  # POST /crafts or /crafts.json
  def create
    @craft = Craft.new(craft_params)

    respond_to do |format|
      if @craft.save
        format.html { redirect_to craft_url(@craft), notice: "Craft was successfully created." }
        format.json { render :show, status: :created, location: @craft }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @craft.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /crafts/1 or /crafts/1.json
  def update
    respond_to do |format|
      if @craft.update(craft_params)
        format.html { redirect_to craft_url(@craft), notice: "Craft was successfully updated." }
        format.json { render :show, status: :ok, location: @craft }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @craft.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /crafts/1 or /crafts/1.json
  def destroy
    @craft.destroy

    respond_to do |format|
      format.html { redirect_to crafts_url, notice: "Craft was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_craft
      @craft = Craft.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def craft_params
      params.require(:craft).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/crafts_helper.rb
module CraftsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/crafts/_craft.html.erb
<div id="<%= dom_id craft %>">
  <p>
    <strong>Name:</strong>
    <%= craft.name %>
  </p>

  <p>
    Posted <%= time_tag craft.created_at, "data-local": "time-ago" %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= craft.description %>
  </p>

</div>

app/views/crafts/_form.html.erb
<%= form_with(model: craft) do |form| %>
  <% if craft.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(craft.errors.count, "error") %> prohibited this craft from being saved:</h2>

      <ul>
        <% craft.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.rich_text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/crafts/edit.html.erb
<h1>Editing craft</h1>

<%= render "form", craft: @craft %>

<br>

<div>
  <%= link_to "Show this craft", @craft %> |
  <%= link_to "Back to crafts", crafts_path %>
</div>

app/views/crafts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Crafts</h1>

<div id="crafts">
  <% @crafts.each do |craft| %>
    <%= render craft %>
    <p>
      <%= link_to "Show this craft", craft %>
    </p>
  <% end %>
</div>

<%= link_to "New craft", new_craft_path %>

app/views/crafts/new.html.erb
<h1>New craft</h1>

<%= render "form", craft: @craft %>

<br>

<div>
  <%= link_to "Back to crafts", crafts_path %>
</div>

app/views/crafts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @craft %>

<div>
  <%= link_to "Edit this craft", edit_craft_path(@craft) %> |
  <%= link_to "Back to crafts", crafts_path %>

  <%= button_to "Destroy this craft", @craft, method: :delete %>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pottercraft</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>